dashboard:
    service_mapping_prefix: dahsboard_service_prefix_
    list:
        default_count_page_item: 2
    mapping:
        book:
            class: AdminBundle\Admin\BookMap
            enabled: true
            entity:
                class: SystemBundle\Entity\Book
        user:
            class: AdminBundle\Admin\UserMap
            enabled: true
            entity:
                class: SystemBundle\Entity\User
