dashboard:
    twig:
        layout: 'DashboardBundle:Layout:layout.html.twig'
        #collection: 'DashboardBundle:Collection:collection.html.twig'
        collection: 'AdminBundle:Example:collection.html.twig'
        form: 'DashboardBundle:Form:form.html.twig'
        menu: 'DashboardBundle:Menu:menu.html.twig'
    service_mapping_prefix: dahsboard_service_prefix_
    list:
        default_count_page_item: 20
    mapping:
        publishing_house:
            class: AdminBundle\Admin\PublishingHouseMap
            enabled: true
            entity:
                class: SystemBundle\Entity\PublishingHouse
        book:
            class: AdminBundle\Admin\BookMap
            enabled: true
            entity:
                class: SystemBundle\Entity\Book
        user:
            class: AdminBundle\Admin\UserMap
            enabled: true
            entity:
                class: SystemBundle\Entity\User

