services:
    # You can specify event listener(handler) when performing converting the field value by service or pass the callback
    year.handler:
        class: AdminBundle\Admin\YearHandler
        tags:
            - { name: kernel.event_listener, event: field.before.getting.value.year , method: handle }
