admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

auth:
    resource: "@AuthBundle/Resources/config/routing.yml"
app:
    resource: "@AppBundle/Resources/config/routing.yml"
