dashboard:
    resource: "@DashboardBundle/Controller/"
    type:     annotation
    prefix:   /dashboard

#admin:
#    resource: "@AdminBundle/Controller/"
#    type:     annotation
#    prefix:   /

auth:
    resource: "@AuthBundle/Resources/config/routing.yml"
app:
    resource: "@AppBundle/Resources/config/routing.yml"
