# http://symfony.com/doc/current/reference/configuration/security.html#reference-security-firewall-form-login
# http://symfony.com/doc/current/cookbook/security/entity_provider.html
# http://symfony.com/doc/current/book/security.html#security-encoding-password
# http://symfony.com/doc/current/cookbook/security/form_login.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

        AppBundle\Entity\User:
            algorithm: bcrypt

        AppBundle\Entity\Admin:
            algorithm: bcrypt

    providers:
        user_provider:
            entity:
                class: AppBundle:User
                property: email

        admin_provider:
            entity:
                class: AppBundle:Admin
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        user_firewall:
            anonymous: ~
            pattern: ^/
            provider: user_provider
            form_login:
                always_use_default_target_path: true
                use_forward: false
                login_path: auth_user_security_login
                check_path: auth_user_security_login
                default_target_path: homepage
            logout:
                path: user_logout
                target: /

        admin_firewall:
            anonymous: ~
            pattern: ^/admin
            provider: admin_provider
            form_login:
                always_use_default_target_path: true
                use_forward: false
                login_path: auth_admin_security_login
                check_path: auth_admin_security_login
                default_target_path: homepage
            logout:
                path: admin_logout
                target: /admin/login

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
