<?php

namespace SystemBundle\Repository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublishingHouseRepository extends \Doctrine\ORM\EntityRepository
{
}
